name: citymapper_like_ui
description: Citymapper like userinterface.
author: Jack Lo <jcluox@gmail.com>
homepage: https://github.com/jcluox/FlutterCitymapperLikeView.git
version: 0.0.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.61.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"